deploy: Use Freight (#183)

diff --git a/kubernetes/zeus/deploy b/kubernetes/zeus/deploy
--- a/kubernetes/zeus/deploy
+++ b/kubernetes/zeus/deploy
@@ -1,51 +1,60 @@
-#!/bin/bash -eux
+#!/bin/bash
+set -eu
 
 . ./config
 
+if [[ "${SENTRY_API_TOKEN:-}" == "" ]]; then
+  echo "SENTRY_API_TOKEN not found in the environment!"
+  exit 1
+fi
+
+set -x
 update_repo
 bind_version
 
 echo "> Deploying ${VERSION:0:7}"
 
+gcloud info
+gcloud container clusters get-credentials zeus --zone "us-central1-b" --project "$PROJECT_ID"
 gcloud container images describe ${IMAGE}:${VERSION}
 
+# Create a Sentry release
 # TODO(dcramer): upload sourcemaps
-if [[ ! -x $SENTRY_API_TOKEN ]]; then
-    curl https://sentry.io/api/0/organizations/sentry/releases/ \
-      -X POST \
-      -H "Authorization: Bearer ${SENTRY_API_TOKEN}" \
-      -H 'Content-Type: application/json' \
-      -d "
-      {
-        \"version\": \"${VERSION}\",
-        \"refs\": [{
-            \"repository\":\"getsentry/zeus\",
-            \"commit\":\"${VERSION}\"
-        }],
-        \"projects\":[\"zeus\"]
-      }
-      "
-fi
+set +x
+curl https://sentry.io/api/0/organizations/sentry/releases/ \
+  -X POST \
+  -H "Authorization: Bearer ${SENTRY_API_TOKEN}" \
+  -H 'Content-Type: application/json' \
+  -d "
+  {
+    \"version\": \"${VERSION}\",
+    \"refs\": [{
+        \"repository\":\"getsentry/zeus\",
+        \"commit\":\"${VERSION}\"
+    }],
+    \"projects\":[\"zeus\"]
+  }
+  "
+set -x
 
 kubectl set image deploy/web zeus=${IMAGE}:${VERSION} --record
 kubectl set image deploy/pubsub zeus=${IMAGE}:${VERSION} --record
 kubectl set image deploy/worker zeus=${IMAGE}:${VERSION} --record
-# kubectl rolling-update web --image=${IMAGE}:${VERSION} --image-pull-policy="IfNotPresent" --container=zeus
-# kubectl rolling-update worker --image=${IMAGE}:${VERSION} --image-pull-policy="IfNotPresent" --container=zeus
 
 kubectl rollout status deployments web
 kubectl rollout status deployments pubsub
 kubectl rollout status deployments worker
 
-if [[ ! -x $SENTRY_API_TOKEN ]]; then
-    curl https://sentry.io/api/0/organizations/sentry/releases/${VERSION}/deploys/ \
-      -X POST \
-      -H "Authorization: Bearer ${SENTRY_API_TOKEN}" \
-      -H 'Content-Type: application/json' \
-      -d '
-      {
-        "environment": "production",
-        "name": "zeus"
-      }
-      '
-fi
+# Create a Sentry deploy
+set +x
+curl https://sentry.io/api/0/organizations/sentry/releases/${VERSION}/deploys/ \
+  -X POST \
+  -H "Authorization: Bearer ${SENTRY_API_TOKEN}" \
+  -H 'Content-Type: application/json' \
+  -d '
+  {
+    "environment": "production",
+    "name": "zeus"
+  }
+  '
+set -x
